# Generated by OmopViewer 0.3.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    "Database characterisation"
  ),
  theme = bslib::bs_theme(bootswatch = "flatly"),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("camera"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_cdm_name",
          label = "CDM name",
          choices = choices$summarise_omop_snapshot_cdm_name,
          selected = selected$summarise_omop_snapshot_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_variable_name",
          label = "Variable name",
          choices = choices$summarise_omop_snapshot_variable_name,
          selected = selected$summarise_omop_snapshot_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Snapshot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_omop_snapshot_table") |>
              shinycssloaders::withSpinner()
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Population Characteristics",
    icon = shiny::icon("users-gear"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_cdm_name",
          label = "CDM name",
          choices = choices$summarise_characteristics_cdm_name,
          selected = selected$summarise_characteristics_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_cohort_name",
          label = "Cohort name",
          choices = choices$summarise_characteristics_cohort_name,
          selected = selected$summarise_characteristics_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_sex",
          label = "Sex",
          choices = choices$summarise_characteristics_sex,
          selected = selected$summarise_characteristics_sex,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_variable_name",
          label = "Variable name",
          choices = choices$summarise_characteristics_variable_name,
          selected = selected$summarise_characteristics_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_characteristics_estimate_name,
          selected = selected$summarise_characteristics_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Characteristics",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("sex", "variable_name", "variable_level", "estimate_name"),
                    input_id = "summarise_characteristics_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = c("cdm_name", "cohort_name"),
                    input_id = "summarise_characteristics_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "summarise_characteristics_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = "table_name",
                    input_id = "summarise_characteristics_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_characteristics_table") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot Characteristics",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_characteristics_plot_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_characteristics_plot_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "summarise_characteristics_plot_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_plot_type",
                  label = "Plot type",
                  choices = c("boxplot", "barplot", "scatterplot"),
                  selected = "barplot",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_facet",
                  label = "Facet",
                  choices = c("cdm_name", "cohort_name", "sex"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_colour",
                  label = "Colour",
                  choices = c("cdm_name", "cohort_name", "sex"),
                  selected = "cohort_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_variable",
                  label = "Variable",
                  choices = c("Number records", "Number subjects", "Cohort start date", "Cohort end date", "Age", "Sex", "Prior observation", "Future observation", "Days in cohort"),
                  selected = "Number subjects",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_characteristics_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Observation Period",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "In Observation",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_cdm_name",
            label = "CDM name",
            choices = choices$summarise_in_observation_cdm_name,
            selected = selected$summarise_in_observation_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_omop_table",
            label = "Omop table",
            choices = choices$summarise_in_observation_omop_table,
            selected = selected$summarise_in_observation_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_sex",
            label = "Sex",
            choices = choices$summarise_in_observation_sex,
            selected = selected$summarise_in_observation_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_age_group",
            label = "Age group",
            choices = choices$summarise_in_observation_age_group,
            selected = selected$summarise_in_observation_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_interval",
            label = "Interval",
            choices = choices$summarise_in_observation_interval,
            selected = selected$summarise_in_observation_interval,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_study_period_end",
            label = "Study period end",
            choices = choices$summarise_in_observation_study_period_end,
            selected = selected$summarise_in_observation_study_period_end,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_study_period_start",
            label = "Study period start",
            choices = choices$summarise_in_observation_study_period_start,
            selected = selected$summarise_in_observation_study_period_start,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_variable_name",
            label = "Variable name",
            choices = choices$summarise_in_observation_variable_name,
            selected = selected$summarise_in_observation_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_in_observation_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_in_observation_estimate_name,
            selected = selected$summarise_in_observation_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_in_observation_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_in_observation_tidy_columns",
                    label = "Columns",
                    choices = c("cdm_name", "omop_table", "sex", "age_group", "interval", "study_period_end", "study_period_start", "variable_name", "variable_level"),
                    selected = c("cdm_name", "omop_table", "sex", "age_group", "variable_name", "variable_level"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_in_observation_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                DT::DTOutput("summarise_in_observation_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot in observation",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_in_observation_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_in_observation_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_in_observation_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_in_observation_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_in_observation_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_in_observation_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "omop_table", "sex", "age_group", "interval", "study_period_end", "study_period_start"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_in_observation_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "omop_table", "sex", "age_group", "interval", "study_period_end", "study_period_start"),
                    selected = character(),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_in_observation_plot_variable",
                    label = "Variable",
                    choices = c("Number person-days", "Number records in observation", "Number subjects in observation", "Number females in observation", "Median age in observation"),
                    selected = "Number records in observation",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_in_observation_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Observation period",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_cdm_name",
            label = "CDM name",
            choices = choices$summarise_observation_period_cdm_name,
            selected = selected$summarise_observation_period_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_observation_period_ordinal",
            label = "Observation period ordinal",
            choices = choices$summarise_observation_period_observation_period_ordinal,
            selected = selected$summarise_observation_period_observation_period_ordinal,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_age_group",
            label = "Age group",
            choices = choices$summarise_observation_period_age_group,
            selected = selected$summarise_observation_period_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_sex",
            label = "Sex",
            choices = choices$summarise_observation_period_sex,
            selected = selected$summarise_observation_period_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_variable_name",
            label = "Variable name",
            choices = choices$summarise_observation_period_variable_name,
            selected = selected$summarise_observation_period_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_observation_period_estimate_name,
            selected = selected$summarise_observation_period_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration in days", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "observation_period_ordinal",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Quality",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Missing data",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_cdm_name",
            label = "CDM name",
            choices = choices$summarise_missing_data_cdm_name,
            selected = selected$summarise_missing_data_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_omop_table",
            label = "Omop table",
            choices = choices$summarise_missing_data_omop_table,
            selected = selected$summarise_missing_data_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_age_group",
            label = "Age group",
            choices = choices$summarise_missing_data_age_group,
            selected = selected$summarise_missing_data_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_sex",
            label = "Sex",
            choices = choices$summarise_missing_data_sex,
            selected = selected$summarise_missing_data_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_study_period_end",
            label = "Study period end",
            choices = choices$summarise_missing_data_study_period_end,
            selected = selected$summarise_missing_data_study_period_end,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_study_period_start",
            label = "Study period start",
            choices = choices$summarise_missing_data_study_period_start,
            selected = selected$summarise_missing_data_study_period_start,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_variable_name",
            label = "Variable name",
            choices = choices$summarise_missing_data_variable_name,
            selected = selected$summarise_missing_data_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_missing_data_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_missing_data_estimate_name,
            selected = selected$summarise_missing_data_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_missing_data_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_missing_data_tidy_columns",
                    label = "Columns",
                    choices = c("cdm_name", "omop_table", "age_group", "sex", "study_period_end", "study_period_start", "variable_name", "variable_level"),
                    selected = c("cdm_name", "omop_table", "age_group", "sex", "variable_name", "variable_level"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_missing_data_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                DT::DTOutput("summarise_missing_data_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table Missing data",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_missing_data_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_missing_data_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_missing_data_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Summarise table quality",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_cdm_name",
            label = "CDM name",
            choices = choices$summarise_table_quality_cdm_name,
            selected = selected$summarise_table_quality_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_omop_table",
            label = "Omop table",
            choices = choices$summarise_table_quality_omop_table,
            selected = selected$summarise_table_quality_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_sex",
            label = "Sex",
            choices = choices$summarise_table_quality_sex,
            selected = selected$summarise_table_quality_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_age_group",
            label = "Age group",
            choices = choices$summarise_table_quality_age_group,
            selected = selected$summarise_table_quality_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_variable_name",
            label = "Variable name",
            choices = choices$summarise_table_quality_variable_name,
            selected = selected$summarise_table_quality_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_table_quality_estimate_name,
            selected = selected$summarise_table_quality_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_study_period_end",
            label = "Study period end",
            choices = choices$summarise_table_quality_study_period_end,
            selected = selected$summarise_table_quality_study_period_end,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_quality_study_period_start",
            label = "Study period start",
            choices = choices$summarise_table_quality_study_period_start,
            selected = selected$summarise_table_quality_study_period_start,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_table_quality_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_table_quality_tidy_columns",
                    label = "Columns",
                    choices = c("cdm_name", "omop_table", "sex", "age_group", "study_period_end", "study_period_start", "variable_name", "variable_level"),
                    selected = c("cdm_name", "omop_table", "sex", "age_group", "variable_name", "variable_level"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_table_quality_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                DT::DTOutput("summarise_table_quality_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_table_quality_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_table_quality_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cdm_name", "omop_table", "sex", "age_group", "study_period_end", "study_period_start", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_table_quality_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = character(),
                      input_id = "summarise_table_quality_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_table_quality_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "summarise_table_quality_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_table_quality_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Clinical Tables",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Clinical records",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_cdm_name",
            label = "CDM name",
            choices = choices$summarise_clinical_records_cdm_name,
            selected = selected$summarise_clinical_records_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_omop_table",
            label = "Omop table",
            choices = choices$summarise_clinical_records_omop_table,
            selected = selected$summarise_clinical_records_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_age_group",
            label = "Age group",
            choices = choices$summarise_clinical_records_age_group,
            selected = selected$summarise_clinical_records_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_sex",
            label = "Sex",
            choices = choices$summarise_clinical_records_sex,
            selected = selected$summarise_clinical_records_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_study_period_end",
            label = "Study period end",
            choices = choices$summarise_clinical_records_study_period_end,
            selected = selected$summarise_clinical_records_study_period_end,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_study_period_start",
            label = "Study period start",
            choices = choices$summarise_clinical_records_study_period_start,
            selected = selected$summarise_clinical_records_study_period_start,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_variable_name",
            label = "Variable name",
            choices = choices$summarise_clinical_records_variable_name,
            selected = selected$summarise_clinical_records_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_clinical_records_estimate_name,
            selected = selected$summarise_clinical_records_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_clinical_records_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_clinical_records_tidy_columns",
                    label = "Columns",
                    choices = c("cdm_name", "omop_table", "age_group", "sex", "study_period_end", "study_period_start", "variable_name", "variable_level"),
                    selected = c("cdm_name", "omop_table", "age_group", "sex", "variable_name", "variable_level"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_clinical_records_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                DT::DTOutput("summarise_clinical_records_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table Clinical records",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_clinical_records_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_clinical_records_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_clinical_records_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Record count",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_cdm_name",
            label = "CDM name",
            choices = choices$summarise_record_count_cdm_name,
            selected = selected$summarise_record_count_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_omop_table",
            label = "Omop table",
            choices = choices$summarise_record_count_omop_table,
            selected = selected$summarise_record_count_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_age_group",
            label = "Age group",
            choices = choices$summarise_record_count_age_group,
            selected = selected$summarise_record_count_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_sex",
            label = "Sex",
            choices = choices$summarise_record_count_sex,
            selected = selected$summarise_record_count_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_interval",
            label = "Interval",
            choices = choices$summarise_record_count_interval,
            selected = selected$summarise_record_count_interval,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_study_period_end",
            label = "Study period end",
            choices = choices$summarise_record_count_study_period_end,
            selected = selected$summarise_record_count_study_period_end,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_study_period_start",
            label = "Study period start",
            choices = choices$summarise_record_count_study_period_start,
            selected = selected$summarise_record_count_study_period_start,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_variable_name",
            label = "Variable name",
            choices = choices$summarise_record_count_variable_name,
            selected = selected$summarise_record_count_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_record_count_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_record_count_estimate_name,
            selected = selected$summarise_record_count_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_record_count_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_record_count_tidy_columns",
                    label = "Columns",
                    choices = c("cdm_name", "omop_table", "age_group", "sex", "interval", "study_period_end", "study_period_start", "variable_name", "variable_level"),
                    selected = c("cdm_name", "omop_table", "age_group", "sex", "variable_name", "variable_level"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_record_count_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                DT::DTOutput("summarise_record_count_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot record count",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_record_count_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_record_count_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_record_count_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_record_count_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_record_count_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_record_count_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "omop_table", "age_group", "sex", "interval", "study_period_end", "study_period_start"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_record_count_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "omop_table", "age_group", "sex", "interval", "study_period_end", "study_period_start"),
                    selected = "omop_table",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_record_count_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.3.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
